# Generated by Django 5.0.7 on 2024-07-16 11:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='000-000-0000', max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
