# Generated by Django 5.0.7 on 2024-07-16 11:22

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+995-000-000-000', max_length=128, region=None, unique=True),
        ),
    ]
